export const bookGenres: string[] = [
    'Literary Fiction',
    'Historical Fiction',
    'Science Fiction',
    'Fantasy',
    'Mystery',
    "Thriller",
    'Romance',
    'Adventure',
    'Biography',
    'Memoir',
    'Self-Help',
    'History',
    'Science',
    'True Crime',
    'Travel',
    'Essays',
    'Picture Books',
    'Middle Grade',
    'Young Adult (YA)',
    'Children\'s Fantasy',
    'Children\'s Mystery',
    'Mystery',
    'Thriller',
    'Crime',
    'Detective Fiction',
    'Space Opera',
    'Cyberpunk',
    'Dystopian',
    'Epic Fantasy',
    'Urban Fantasy',
    'Contemporary Romance',
    'Historical Romance',
    'Paranormal Romance',
    'Romantic Suspense',
    'Psychological Horror',
    'Supernatural Horror',
    'Gothic Horror',
    'Zombie Fiction',
    'Contemporary Poetry',
    'Classic Poetry',
    'Slam Poetry',
    'Haiku',
    'Contemporary Drama',
    'Historical Drama',
    'Family Drama',
    'Satire',
    'Comedy',
    'Dark Comedy',
    'Superhero',
    'Manga',
    'Graphic Memoir',
];


